"""complete_schema

Revision ID: 559fa082f874
Revises: fc1c13362cbc
Create Date: 2026-02-04 21:49:27.215965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559fa082f874'
down_revision: Union[str, None] = 'fc1c13362cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: composite_alert_rules already created in fc1c13362cbc_initial_schema.py
    # Removed duplicate table creation to fix migration conflict

    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel_type IN ('email', 'slack', 'webhook')", name='valid_template_channel_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_templates_channel', 'notification_templates', ['channel_type'], unique=False)
    op.create_index('idx_notification_templates_enabled', 'notification_templates', ['enabled'], unique=False)
    op.create_index('idx_notification_templates_tenant', 'notification_templates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel_type IN ('email', 'slack', 'webhook', 'apns', 'fcm', 'sms')", name='valid_notification_channel_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_channels_enabled', 'notification_channels', ['enabled'], unique=False)
    op.create_index('idx_notification_channels_tenant', 'notification_channels', ['tenant_id'], unique=False)
    op.create_index('idx_notification_channels_type', 'notification_channels', ['channel_type'], unique=False)
    op.create_index('idx_notification_channels_user', 'notification_channels', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_channels_tenant_id'), 'notification_channels', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_rules_alert', 'notification_rules', ['alert_rule_id'], unique=False)
    op.create_index('idx_notification_rules_channel', 'notification_rules', ['channel_id'], unique=False)
    op.create_index('idx_notification_rules_enabled', 'notification_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_notification_rules_alert_rule_id'), 'notification_rules', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_channel_id'), 'notification_rules', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_tenant_id'), 'notification_rules', ['tenant_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='valid_notification_queue_status'),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_queue_created', 'notification_queue', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_notification_queue_retry', 'notification_queue', ['status', 'created_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('idx_notification_queue_status', 'notification_queue', ['status'], unique=False)
    op.create_index('idx_notification_queue_tenant', 'notification_queue', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_alert_event_id'), 'notification_queue', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_tenant_id'), 'notification_queue', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_event_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("delivery_status IS NULL OR delivery_status IN ('success', 'permanent_failure', 'temporary_failure', 'invalid_address', 'rate_limited')", name='valid_delivery_status'),
    sa.CheckConstraint("status IN ('pending', 'sending', 'sent', 'failed', 'bounced', 'skipped')", name='valid_notification_status'),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_alert_event', 'notifications', ['alert_event_id'], unique=False)
    op.create_index('idx_notifications_channel', 'notifications', ['channel_id'], unique=False)
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_recipient', 'notifications', ['recipient'], unique=False)
    op.create_index('idx_notifications_retry', 'notifications', ['status', 'next_retry_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notifications_tenant', 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_alert_event_id'), 'notifications', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel_id'), 'notifications', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.drop_table('schema_migrations')
    op.drop_index('idx_alarms_acknowledged_by', table_name='alarms')
    op.drop_index('idx_alarms_alert_rule', table_name='alarms')
    op.drop_index('idx_alarms_device', table_name='alarms')
    op.drop_index('idx_alarms_fired_at', table_name='alarms')
    op.drop_index('idx_alarms_severity', table_name='alarms')
    op.drop_index('idx_alarms_status', table_name='alarms')
    op.drop_index('idx_alarms_tenant', table_name='alarms')
    op.drop_index('idx_alarms_type', table_name='alarms')
    op.create_index('idx_alarms_acknowledged', 'alarms', ['acknowledged_by'], unique=False, postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.create_index('idx_alarms_active', 'alarms', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_alarms_acknowledged_by'), 'alarms', ['acknowledged_by'], unique=False)
    op.create_index(op.f('ix_alarms_alarm_type'), 'alarms', ['alarm_type'], unique=False)
    op.create_index(op.f('ix_alarms_alert_rule_id'), 'alarms', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alarms_device_id'), 'alarms', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarms_fired_at'), 'alarms', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alarms_severity'), 'alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_alarms_status'), 'alarms', ['status'], unique=False)
    op.create_index(op.f('ix_alarms_tenant_id'), 'alarms', ['tenant_id'], unique=False)
    op.add_column('alert_events', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('alert_events', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('alert_events', sa.Column('alarm_type', sa.String(length=100), nullable=True))
    op.add_column('alert_events', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('alert_events', sa.Column('acknowledged_by', sa.UUID(), nullable=True))
    op.add_column('alert_events', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert_events', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('alert_events', 'alert_rule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alert_events', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_alert_events_fired_at', table_name='alert_events')
    op.drop_index('idx_alert_events_tenant', table_name='alert_events')
    op.create_index('idx_alert_events_alarm_type', 'alert_events', ['tenant_id', 'alarm_type', 'status'], unique=False)
    op.create_index('idx_alert_events_severity', 'alert_events', ['severity'], unique=False)
    op.create_index('idx_alert_events_status', 'alert_events', ['status'], unique=False)
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_device_id'), 'alert_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_events_fired_at'), 'alert_events', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alert_events_tenant_id'), 'alert_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'alert_events', 'users', ['acknowledged_by'], ['id'], ondelete='SET NULL')
    op.alter_column('alert_rule_conditions', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index('idx_rule_conditions_rule', table_name='alert_rule_conditions')
    op.create_index('idx_alert_conditions_rule', 'alert_rule_conditions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_rule_conditions_rule_id'), 'alert_rule_conditions', ['rule_id'], unique=False)
    op.add_column('alert_rules', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('alert_rules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('alert_rules', sa.Column('rule_type', sa.String(length=20), nullable=False))
    op.add_column('alert_rules', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('alert_rules', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('alert_rules', sa.Column('logic', sa.String(length=10), nullable=True))
    op.alter_column('alert_rules', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alert_rules', 'metric',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alert_rules', 'operator',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('alert_rules', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('alert_rules', 'cooldown_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('alert_rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_alert_rules_tenant', table_name='alert_rules')
    op.create_index(op.f('ix_alert_rules_active'), 'alert_rules', ['active'], unique=False)
    op.create_index(op.f('ix_alert_rules_device_id'), 'alert_rules', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_severity'), 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_tenant', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.alter_column('dashboard_widgets', 'widget_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Widget type: kpi_card, chart, gauge, map, table, device_info, etc.',
               existing_nullable=False)
    op.alter_column('dashboard_widgets', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Widget-specific configuration (chart type, colors, thresholds, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboard_widgets', 'data_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='Array of device IDs and metrics bound to this widget',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('dashboard_widgets', 'refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Auto-refresh interval in seconds',
               existing_server_default=sa.text('30'))
    op.alter_column('dashboard_widgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboard_widgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.drop_table_comment(
        'dashboard_widgets',
        existing_comment='Individual widgets placed on dashboards with configuration and data bindings',
        schema=None
    )
    op.alter_column('dashboards', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Whether this dashboard is shown by default on login',
               existing_server_default=sa.text('false'))
    op.alter_column('dashboards', 'layout_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='Grid layout configuration including breakpoints and column settings',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'theme',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='Dashboard-specific color scheme and branding',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'solution_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identifier of the solution template used to create this dashboard',
               existing_nullable=True)
    op.alter_column('dashboards', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_dashboards_created_at', table_name='dashboards')
    op.create_index('idx_dashboards_created_at', 'dashboards', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboards_tenant_id'), 'dashboards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.drop_table_comment(
        'dashboards',
        existing_comment='User-created dashboards with customizable layouts and widgets',
        schema=None
    )
    op.drop_index('idx_creds_status', table_name='device_credentials')
    op.create_index(op.f('ix_device_credentials_tenant_id'), 'device_credentials', ['tenant_id'], unique=False)
    op.add_column('device_groups', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('device_groups', sa.Column('site_id', sa.UUID(), nullable=True))
    op.add_column('device_groups', sa.Column('group_type', sa.String(length=50), nullable=True))
    op.add_column('device_groups', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('device_groups', 'membership_rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint('unique_group_name_per_tenant', 'device_groups', type_='unique')
    op.create_index('idx_device_groups_org', 'device_groups', ['organization_id'], unique=False)
    op.create_index('idx_device_groups_site', 'device_groups', ['site_id'], unique=False)
    op.create_index(op.f('ix_device_groups_organization_id'), 'device_groups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_device_groups_site_id'), 'device_groups', ['site_id'], unique=False)
    op.create_index(op.f('ix_device_groups_tenant_id'), 'device_groups', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'device_groups', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_groups', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('device_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('device_types', 'manufacturer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('device_types', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('device_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('device_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('device_types', 'device_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('device_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('device_types_name_tenant_unique', 'device_types', type_='unique')
    op.drop_index('idx_device_types_capabilities', table_name='device_types', postgresql_using='gin')
    op.drop_index('idx_device_types_data_model', table_name='device_types', postgresql_using='gin')
    op.drop_index('idx_device_types_is_active', table_name='device_types')
    op.drop_index('idx_device_types_manufacturer', table_name='device_types')
    op.drop_index('idx_device_types_tenant_id', table_name='device_types')
    op.create_index('idx_device_types_active', 'device_types', ['is_active'], unique=False)
    op.create_index('idx_device_types_tenant', 'device_types', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_types_tenant_id'), 'device_types', ['tenant_id'], unique=False)
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'offline'::character varying"))
    op.alter_column('devices', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_devices_chirpstack_app_id', table_name='devices', postgresql_where='(chirpstack_app_id IS NOT NULL)')
    op.drop_index('idx_devices_chirpstack_synced', table_name='devices', postgresql_where='(NOT chirpstack_synced)')
    op.drop_index('idx_devices_device_group_id', table_name='devices')
    op.drop_index('idx_devices_device_type_id', table_name='devices')
    op.drop_index('idx_devices_organization_id', table_name='devices')
    op.drop_index('idx_devices_site_id', table_name='devices')
    op.drop_index('idx_devices_tenant_id', table_name='devices')
    op.drop_index('idx_devices_last_seen', table_name='devices')
    op.create_index('idx_devices_last_seen', 'devices', ['last_seen'], unique=False)
    op.create_index('idx_devices_group', 'devices', ['device_group_id'], unique=False)
    op.create_index('idx_devices_organization', 'devices', ['organization_id'], unique=False)
    op.create_index('idx_devices_site', 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_device_group_id'), 'devices', ['device_group_id'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.drop_constraint('devices_device_type_id_fkey', 'devices', type_='foreignkey')
    op.drop_column('devices', 'chirpstack_synced')
    op.drop_column('devices', 'device_type_id')
    op.drop_column('devices', 'chirpstack_app_id')
    op.add_column('group_bulk_operations', sa.Column('operation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('group_bulk_operations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'queued'::character varying"))
    op.alter_column('group_bulk_operations', 'devices_completed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('group_bulk_operations', 'devices_failed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('group_bulk_operations', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_bulk_operations_created_at', table_name='group_bulk_operations')
    op.create_index('idx_bulk_operations_created_at', 'group_bulk_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_bulk_operations_group_id'), 'group_bulk_operations', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_bulk_operations_tenant_id'), 'group_bulk_operations', ['tenant_id'], unique=False)
    op.drop_column('group_bulk_operations', 'metadata')
    op.drop_constraint('unique_group_device', 'group_devices', type_='unique')
    op.create_index(op.f('ix_group_devices_device_id'), 'group_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_group_devices_group_id'), 'group_devices', ['group_id'], unique=False)
    op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('billing_contact', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('chirpstack_app_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('organizations', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_organizations_parent_id', table_name='organizations')
    op.drop_index('idx_organizations_tenant_id', table_name='organizations')
    op.drop_constraint('unique_org_name_per_tenant', 'organizations', type_='unique')
    op.create_index('idx_organizations_chirpstack', 'organizations', ['chirpstack_app_id'], unique=False, postgresql_where='chirpstack_app_id IS NOT NULL')
    op.create_index('idx_organizations_slug', 'organizations', ['tenant_id', 'slug'], unique=True)
    op.create_index('idx_organizations_tenant', 'organizations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.drop_constraint('organizations_parent_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'parent_id')
    op.add_column('sites', sa.Column('parent_site_id', sa.UUID(), nullable=True))
    op.add_column('sites', sa.Column('site_type', sa.String(length=50), nullable=True))
    op.add_column('sites', sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sites', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.alter_column('sites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sites', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_sites_organization_id', table_name='sites')
    op.drop_index('idx_sites_tenant_id', table_name='sites')
    op.drop_constraint('unique_site_name_per_tenant', 'sites', type_='unique')
    op.create_index('idx_sites_organization', 'sites', ['organization_id'], unique=False)
    op.create_index('idx_sites_parent', 'sites', ['parent_site_id'], unique=False)
    op.create_index('idx_sites_tenant', 'sites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sites', 'sites', ['parent_site_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sites', 'longitude')
    op.drop_column('sites', 'latitude')
    op.drop_column('sites', 'description')
    op.alter_column('solution_templates', 'identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique slug identifier for the template',
               existing_nullable=False)
    op.alter_column('solution_templates', 'target_device_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='Array of compatible device type identifiers',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solution_templates', 'required_capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='Array of required telemetry capabilities/metrics',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solution_templates', 'template_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Complete dashboard and widget configuration blueprint',
               existing_nullable=False)
    op.alter_column('solution_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('solution_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('solution_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'solution_templates',
        existing_comment='Pre-built industry-specific dashboard templates',
        schema=None
    )
    op.alter_column('telemetry_hot', 'id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('telemetry_hot', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('idx_telemetry_device_time', table_name='telemetry_hot')
    op.create_index('idx_telemetry_device_time', 'telemetry_hot', ['device_id', 'timestamp'], unique=False)
    op.drop_index('idx_telemetry_tenant_device', table_name='telemetry_hot')
    op.create_index('idx_telemetry_tenant_device', 'telemetry_hot', ['tenant_id', 'device_id'], unique=False)
    op.drop_index('idx_telemetry_timestamp', table_name='telemetry_hot')
    op.create_index('idx_telemetry_timestamp', 'telemetry_hot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_device_id'), 'telemetry_hot', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_tenant_id'), 'telemetry_hot', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_timestamp'), 'telemetry_hot', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'telemetry_hot', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('idx_tenants_slug', table_name='tenants')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_constraint('unique_email_per_tenant', 'users', type_='unique')
    op.drop_index('idx_users_tenant_email', table_name='users')
    op.create_index('idx_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('idx_users_tenant_email', table_name='users')
    op.create_index('idx_users_tenant_email', 'users', ['tenant_id', 'email'], unique=False)
    op.create_unique_constraint('unique_email_per_tenant', 'users', ['tenant_id', 'email'])
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_index('idx_tenants_slug', 'tenants', ['slug'], unique=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(None, 'telemetry_hot', type_='foreignkey')
    op.drop_index(op.f('ix_telemetry_hot_timestamp'), table_name='telemetry_hot')
    op.drop_index(op.f('ix_telemetry_hot_tenant_id'), table_name='telemetry_hot')
    op.drop_index(op.f('ix_telemetry_hot_device_id'), table_name='telemetry_hot')
    op.drop_index('idx_telemetry_timestamp', table_name='telemetry_hot')
    op.create_index('idx_telemetry_timestamp', 'telemetry_hot', [sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_telemetry_tenant_device', table_name='telemetry_hot')
    op.create_index('idx_telemetry_tenant_device', 'telemetry_hot', ['tenant_id', 'device_id', sa.text('timestamp DESC')], unique=False)
    op.drop_index('idx_telemetry_device_time', table_name='telemetry_hot')
    op.create_index('idx_telemetry_device_time', 'telemetry_hot', ['device_id', sa.text('timestamp DESC')], unique=False)
    op.alter_column('telemetry_hot', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('telemetry_hot', 'id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table_comment(
        'solution_templates',
        'Pre-built industry-specific dashboard templates',
        existing_comment=None,
        schema=None
    )
    op.alter_column('solution_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('solution_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('solution_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('solution_templates', 'template_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Complete dashboard and widget configuration blueprint',
               existing_nullable=False)
    op.alter_column('solution_templates', 'required_capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='Array of required telemetry capabilities/metrics',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solution_templates', 'target_device_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='Array of compatible device type identifiers',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solution_templates', 'identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique slug identifier for the template',
               existing_nullable=False)
    op.add_column('sites', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index('idx_sites_tenant', table_name='sites')
    op.drop_index('idx_sites_parent', table_name='sites')
    op.drop_index('idx_sites_organization', table_name='sites')
    op.create_unique_constraint('unique_site_name_per_tenant', 'sites', ['tenant_id', 'name'])
    op.create_index('idx_sites_tenant_id', 'sites', ['tenant_id'], unique=False)
    op.create_index('idx_sites_organization_id', 'sites', ['organization_id'], unique=False)
    op.alter_column('sites', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sites', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('sites', 'timezone')
    op.drop_column('sites', 'coordinates')
    op.drop_column('sites', 'site_type')
    op.drop_column('sites', 'parent_site_id')
    op.add_column('organizations', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('organizations_parent_id_fkey', 'organizations', 'organizations', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index('idx_organizations_tenant', table_name='organizations')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_index('idx_organizations_chirpstack', table_name='organizations', postgresql_where='chirpstack_app_id IS NOT NULL')
    op.create_unique_constraint('unique_org_name_per_tenant', 'organizations', ['tenant_id', 'name'])
    op.create_index('idx_organizations_tenant_id', 'organizations', ['tenant_id'], unique=False)
    op.create_index('idx_organizations_parent_id', 'organizations', ['parent_id'], unique=False)
    op.alter_column('organizations', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'chirpstack_app_id')
    op.drop_column('organizations', 'billing_contact')
    op.drop_column('organizations', 'slug')
    op.drop_index(op.f('ix_group_devices_group_id'), table_name='group_devices')
    op.drop_index(op.f('ix_group_devices_device_id'), table_name='group_devices')
    op.create_unique_constraint('unique_group_device', 'group_devices', ['group_id', 'device_id'])
    op.add_column('group_bulk_operations', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_group_bulk_operations_tenant_id'), table_name='group_bulk_operations')
    op.drop_index(op.f('ix_group_bulk_operations_group_id'), table_name='group_bulk_operations')
    op.drop_index('idx_bulk_operations_created_at', table_name='group_bulk_operations')
    op.create_index('idx_bulk_operations_created_at', 'group_bulk_operations', [sa.text('created_at DESC')], unique=False)
    op.alter_column('group_bulk_operations', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('group_bulk_operations', 'devices_failed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('group_bulk_operations', 'devices_completed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('group_bulk_operations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'queued'::character varying"))
    op.drop_column('group_bulk_operations', 'operation_metadata')
    op.add_column('devices', sa.Column('chirpstack_app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('chirpstack_synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_foreign_key('devices_device_type_id_fkey', 'devices', 'device_types', ['device_type_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_group_id'), table_name='devices')
    op.drop_index('idx_devices_site', table_name='devices')
    op.drop_index('idx_devices_organization', table_name='devices')
    op.drop_index('idx_devices_group', table_name='devices')
    op.drop_index('idx_devices_last_seen', table_name='devices')
    op.create_index('idx_devices_last_seen', 'devices', [sa.text('last_seen DESC')], unique=False)
    op.create_index('idx_devices_tenant_id', 'devices', ['tenant_id'], unique=False)
    op.create_index('idx_devices_site_id', 'devices', ['site_id'], unique=False)
    op.create_index('idx_devices_organization_id', 'devices', ['organization_id'], unique=False)
    op.create_index('idx_devices_device_type_id', 'devices', ['device_type_id'], unique=False)
    op.create_index('idx_devices_device_group_id', 'devices', ['device_group_id'], unique=False)
    op.create_index('idx_devices_chirpstack_synced', 'devices', ['chirpstack_synced'], unique=False, postgresql_where='(NOT chirpstack_synced)')
    op.create_index('idx_devices_chirpstack_app_id', 'devices', ['chirpstack_app_id'], unique=False, postgresql_where='(chirpstack_app_id IS NOT NULL)')
    op.alter_column('devices', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'offline'::character varying"))
    op.drop_index(op.f('ix_device_types_tenant_id'), table_name='device_types')
    op.drop_index('idx_device_types_tenant', table_name='device_types')
    op.drop_index('idx_device_types_active', table_name='device_types')
    op.create_index('idx_device_types_tenant_id', 'device_types', ['tenant_id'], unique=False)
    op.create_index('idx_device_types_manufacturer', 'device_types', ['manufacturer'], unique=False)
    op.create_index('idx_device_types_is_active', 'device_types', ['is_active'], unique=False)
    op.create_index('idx_device_types_data_model', 'device_types', ['data_model'], unique=False, postgresql_using='gin')
    op.create_index('idx_device_types_capabilities', 'device_types', ['capabilities'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('device_types_name_tenant_unique', 'device_types', ['tenant_id', 'name'])
    op.alter_column('device_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_types', 'device_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('device_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('device_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('device_types', 'model',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('device_types', 'manufacturer',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('device_types', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'device_groups', type_='foreignkey')
    op.drop_constraint(None, 'device_groups', type_='foreignkey')
    op.drop_index(op.f('ix_device_groups_tenant_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_site_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_organization_id'), table_name='device_groups')
    op.drop_index('idx_device_groups_site', table_name='device_groups')
    op.drop_index('idx_device_groups_org', table_name='device_groups')
    op.create_unique_constraint('unique_group_name_per_tenant', 'device_groups', ['tenant_id', 'name'])
    op.alter_column('device_groups', 'membership_rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('device_groups', 'attributes')
    op.drop_column('device_groups', 'group_type')
    op.drop_column('device_groups', 'site_id')
    op.drop_column('device_groups', 'organization_id')
    op.drop_index(op.f('ix_device_credentials_tenant_id'), table_name='device_credentials')
    op.create_index('idx_creds_status', 'device_credentials', ['status'], unique=False)
    op.create_table_comment(
        'dashboards',
        'User-created dashboards with customizable layouts and widgets',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_dashboards_user_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_tenant_id'), table_name='dashboards')
    op.drop_index('idx_dashboards_created_at', table_name='dashboards')
    op.create_index('idx_dashboards_created_at', 'dashboards', [sa.text('created_at DESC')], unique=False)
    op.alter_column('dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboards', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'solution_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Identifier of the solution template used to create this dashboard',
               existing_nullable=True)
    op.alter_column('dashboards', 'theme',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='Dashboard-specific color scheme and branding',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'layout_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='Grid layout configuration including breakpoints and column settings',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboards', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Whether this dashboard is shown by default on login',
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'dashboard_widgets',
        'Individual widgets placed on dashboards with configuration and data bindings',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.alter_column('dashboard_widgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboard_widgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboard_widgets', 'refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Auto-refresh interval in seconds',
               existing_server_default=sa.text('30'))
    op.alter_column('dashboard_widgets', 'data_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='Array of device IDs and metrics bound to this widget',
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('dashboard_widgets', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Widget-specific configuration (chart type, colors, thresholds, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dashboard_widgets', 'widget_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Widget type: kpi_card, chart, gauge, map, table, device_info, etc.',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index('idx_audit_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_severity'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_device_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_active'), table_name='alert_rules')
    op.create_index('idx_alert_rules_tenant', 'alert_rules', ['tenant_id'], unique=False)
    op.alter_column('alert_rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('alert_rules', 'cooldown_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('alert_rules', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alert_rules', 'operator',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('alert_rules', 'metric',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('alert_rules', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('alert_rules', 'logic')
    op.drop_column('alert_rules', 'conditions')
    op.drop_column('alert_rules', 'severity')
    op.drop_column('alert_rules', 'rule_type')
    op.drop_column('alert_rules', 'description')
    op.drop_column('alert_rules', 'name')
    op.drop_index(op.f('ix_alert_rule_conditions_rule_id'), table_name='alert_rule_conditions')
    op.drop_index('idx_alert_conditions_rule', table_name='alert_rule_conditions')
    op.create_index('idx_rule_conditions_rule', 'alert_rule_conditions', ['rule_id'], unique=False)
    op.alter_column('alert_rule_conditions', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.drop_index(op.f('ix_alert_events_tenant_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_fired_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_device_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_index('idx_alert_events_status', table_name='alert_events')
    op.drop_index('idx_alert_events_severity', table_name='alert_events')
    op.drop_index('idx_alert_events_alarm_type', table_name='alert_events')
    op.create_index('idx_alert_events_tenant', 'alert_events', ['tenant_id'], unique=False)
    op.create_index('idx_alert_events_fired_at', 'alert_events', [sa.text('fired_at DESC')], unique=False)
    op.alter_column('alert_events', 'notification_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_events', 'alert_rule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('alert_events', 'cleared_at')
    op.drop_column('alert_events', 'acknowledged_at')
    op.drop_column('alert_events', 'acknowledged_by')
    op.drop_column('alert_events', 'source')
    op.drop_column('alert_events', 'alarm_type')
    op.drop_column('alert_events', 'status')
    op.drop_column('alert_events', 'severity')
    op.drop_index(op.f('ix_alarms_tenant_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_status'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_severity'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_fired_at'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_device_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alert_rule_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alarm_type'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_acknowledged_by'), table_name='alarms')
    op.drop_index('idx_alarms_active', table_name='alarms', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_alarms_acknowledged', table_name='alarms', postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.create_index('idx_alarms_type', 'alarms', ['alarm_type'], unique=False)
    op.create_index('idx_alarms_tenant', 'alarms', ['tenant_id'], unique=False)
    op.create_index('idx_alarms_status', 'alarms', ['status'], unique=False)
    op.create_index('idx_alarms_severity', 'alarms', ['severity'], unique=False)
    op.create_index('idx_alarms_fired_at', 'alarms', ['fired_at'], unique=False)
    op.create_index('idx_alarms_device', 'alarms', ['device_id'], unique=False)
    op.create_index('idx_alarms_alert_rule', 'alarms', ['alert_rule_id'], unique=False)
    op.create_index('idx_alarms_acknowledged_by', 'alarms', ['acknowledged_by'], unique=False)
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name='schema_migrations_pkey')
    )
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_event_id'), table_name='notifications')
    op.drop_index('idx_notifications_tenant', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_index('idx_notifications_retry', table_name='notifications', postgresql_where="status = 'pending'")
    op.drop_index('idx_notifications_recipient', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_index('idx_notifications_channel', table_name='notifications')
    op.drop_index('idx_notifications_alert_event', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_queue_tenant_id'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_alert_event_id'), table_name='notification_queue')
    op.drop_index('idx_notification_queue_tenant', table_name='notification_queue')
    op.drop_index('idx_notification_queue_status', table_name='notification_queue')
    op.drop_index('idx_notification_queue_retry', table_name='notification_queue', postgresql_where="status = 'pending'")
    op.drop_index('idx_notification_queue_created', table_name='notification_queue', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_notification_rules_tenant_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_channel_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_alert_rule_id'), table_name='notification_rules')
    op.drop_index('idx_notification_rules_enabled', table_name='notification_rules')
    op.drop_index('idx_notification_rules_channel', table_name='notification_rules')
    op.drop_index('idx_notification_rules_alert', table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_tenant_id'), table_name='notification_channels')
    op.drop_index('idx_notification_channels_user', table_name='notification_channels')
    op.drop_index('idx_notification_channels_type', table_name='notification_channels')
    op.drop_index('idx_notification_channels_tenant', table_name='notification_channels')
    op.drop_index('idx_notification_channels_enabled', table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_index('idx_notification_templates_tenant', table_name='notification_templates')
    op.drop_index('idx_notification_templates_enabled', table_name='notification_templates')
    op.drop_index('idx_notification_templates_channel', table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_composite_alert_rules_tenant_id'), table_name='composite_alert_rules')
    op.drop_index(op.f('ix_composite_alert_rules_severity'), table_name='composite_alert_rules')
    op.drop_index(op.f('ix_composite_alert_rules_enabled'), table_name='composite_alert_rules')
    op.drop_table('composite_alert_rules')
    # ### end Alembic commands ###
