"""Initial schema

Revision ID: fc1c13362cbc
Revises: 
Create Date: 2026-02-04 17:33:13.266987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc1c13362cbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('logic', sa.String(length=10), server_default=sa.text("'AND'"), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('weight_score', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("logic IN ('AND', 'OR')", name='valid_logic'),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='valid_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composite_alert_rules_enabled'), 'composite_alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_composite_alert_rules_severity'), 'composite_alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_composite_alert_rules_tenant_id'), 'composite_alert_rules', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='valid_tenant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel_type IN ('email', 'slack', 'webhook')", name='valid_template_channel_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_templates_channel', 'notification_templates', ['channel_type'], unique=False)
    op.create_index('idx_notification_templates_enabled', 'notification_templates', ['enabled'], unique=False)
    op.create_index('idx_notification_templates_tenant', 'notification_templates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billing_contact', sa.String(length=255), nullable=True),
    sa.Column('chirpstack_app_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='valid_org_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organizations_chirpstack', 'organizations', ['chirpstack_app_id'], unique=False, postgresql_where='chirpstack_app_id IS NOT NULL')
    op.create_index('idx_organizations_slug', 'organizations', ['tenant_id', 'slug'], unique=True)
    op.create_index('idx_organizations_tenant', 'organizations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'TENANT_ADMIN', 'SITE_ADMIN', 'CLIENT', 'VIEWER')", name='valid_user_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel_type IN ('email', 'slack', 'webhook', 'apns', 'fcm', 'sms')", name='valid_notification_channel_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_channels_enabled', 'notification_channels', ['enabled'], unique=False)
    op.create_index('idx_notification_channels_tenant', 'notification_channels', ['tenant_id'], unique=False)
    op.create_index('idx_notification_channels_type', 'notification_channels', ['channel_type'], unique=False)
    op.create_index('idx_notification_channels_user', 'notification_channels', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_channels_tenant_id'), 'notification_channels', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_site_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sites_organization', 'sites', ['organization_id'], unique=False)
    op.create_index('idx_sites_parent', 'sites', ['parent_site_id'], unique=False)
    op.create_index('idx_sites_tenant', 'sites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('device_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('membership_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_groups_org', 'device_groups', ['organization_id'], unique=False)
    op.create_index('idx_device_groups_site', 'device_groups', ['site_id'], unique=False)
    op.create_index('idx_device_groups_tenant', 'device_groups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_groups_organization_id'), 'device_groups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_device_groups_site_id'), 'device_groups', ['site_id'], unique=False)
    op.create_index(op.f('ix_device_groups_tenant_id'), 'device_groups', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('device_group_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('dev_eui', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ttn_app_id', sa.String(length=100), nullable=True),
    sa.Column('device_profile_id', sa.String(length=100), nullable=True),
    sa.Column('ttn_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('online', 'offline', 'idle', 'error', 'provisioning')", name='valid_device_status'),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_devices_group', 'devices', ['device_group_id'], unique=False)
    op.create_index('idx_devices_last_seen', 'devices', ['last_seen'], unique=False)
    op.create_index('idx_devices_organization', 'devices', ['organization_id'], unique=False)
    op.create_index('idx_devices_site', 'devices', ['site_id'], unique=False)
    op.create_index('idx_devices_status', 'devices', ['status'], unique=False)
    op.create_index('idx_devices_tenant_dev_eui', 'devices', ['tenant_id', 'dev_eui'], unique=True)
    op.create_index(op.f('ix_devices_device_group_id'), 'devices', ['device_group_id'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('group_bulk_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cadence_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('devices_total', sa.Integer(), nullable=False),
    sa.Column('devices_completed', sa.Integer(), nullable=False),
    sa.Column('devices_failed', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('operation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_operations_created_at', 'group_bulk_operations', ['created_at'], unique=False)
    op.create_index('idx_bulk_operations_group', 'group_bulk_operations', ['group_id'], unique=False)
    op.create_index('idx_bulk_operations_status', 'group_bulk_operations', ['status'], unique=False)
    op.create_index('idx_bulk_operations_tenant', 'group_bulk_operations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_group_bulk_operations_group_id'), 'group_bulk_operations', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_bulk_operations_tenant_id'), 'group_bulk_operations', ['tenant_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logic', sa.String(length=10), nullable=True),
    sa.CheckConstraint("metric IN ('temperature', 'humidity', 'battery', 'rssi', 'pressure')", name='valid_alert_metric'),
    sa.CheckConstraint("operator IN ('gt', 'gte', 'lt', 'lte', 'eq', 'neq')", name='valid_alert_operator'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_rules_active', 'alert_rules', ['active'], unique=False)
    op.create_index('idx_alert_rules_device', 'alert_rules', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_active'), 'alert_rules', ['active'], unique=False)
    op.create_index(op.f('ix_alert_rules_device_id'), 'alert_rules', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_severity'), 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('credential_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("credential_type IN ('mqtt_password', 'device_token', 'api_key')", name='valid_cred_type'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_creds_tenant_device', 'device_credentials', ['tenant_id', 'device_id'], unique=False)
    op.create_index(op.f('ix_device_credentials_tenant_id'), 'device_credentials', ['tenant_id'], unique=False)
    op.create_table('group_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_devices_device', 'group_devices', ['device_id'], unique=False)
    op.create_index('idx_group_devices_group', 'group_devices', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_devices_device_id'), 'group_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_group_devices_group_id'), 'group_devices', ['group_id'], unique=False)
    op.create_table('telemetry_hot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_device_time', 'telemetry_hot', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_telemetry_tenant_device', 'telemetry_hot', ['tenant_id', 'device_id'], unique=False)
    op.create_index('idx_telemetry_timestamp', 'telemetry_hot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_device_id'), 'telemetry_hot', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_tenant_id'), 'telemetry_hot', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_telemetry_hot_timestamp'), 'telemetry_hot', ['timestamp'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('alarm_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'MAJOR', 'MINOR', 'WARNING')", name='valid_severity'),
    sa.CheckConstraint("status IN ('ACTIVE', 'ACKNOWLEDGED', 'CLEARED')", name='valid_alarm_status'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alarms_acknowledged', 'alarms', ['acknowledged_by'], unique=False, postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.create_index('idx_alarms_active', 'alarms', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_alarms_acknowledged_by'), 'alarms', ['acknowledged_by'], unique=False)
    op.create_index(op.f('ix_alarms_alarm_type'), 'alarms', ['alarm_type'], unique=False)
    op.create_index(op.f('ix_alarms_alert_rule_id'), 'alarms', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alarms_device_id'), 'alarms', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarms_fired_at'), 'alarms', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alarms_severity'), 'alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_alarms_status'), 'alarms', ['status'], unique=False)
    op.create_index(op.f('ix_alarms_tenant_id'), 'alarms', ['tenant_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('alarm_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'MAJOR', 'MINOR', 'WARNING')", name='valid_severity'),
    sa.CheckConstraint("status IN ('ACTIVE', 'ACKNOWLEDGED', 'CLEARED')", name='valid_alarm_status'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_events_alarm_type', 'alert_events', ['tenant_id', 'alarm_type', 'status'], unique=False)
    op.create_index('idx_alert_events_device', 'alert_events', ['device_id'], unique=False)
    op.create_index('idx_alert_events_rule', 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index('idx_alert_events_severity', 'alert_events', ['severity'], unique=False)
    op.create_index('idx_alert_events_status', 'alert_events', ['status'], unique=False)
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_device_id'), 'alert_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_events_fired_at'), 'alert_events', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alert_events_tenant_id'), 'alert_events', ['tenant_id'], unique=False)
    op.create_table('alert_rule_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operator IN ('>', '<', '>=', '<=', '==', '!=')", name='valid_condition_operator'),
    sa.CheckConstraint('weight >= 1 AND weight <= 100', name='valid_condition_weight'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_conditions_rule', 'alert_rule_conditions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_rule_conditions_rule_id'), 'alert_rule_conditions', ['rule_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_rules_alert', 'notification_rules', ['alert_rule_id'], unique=False)
    op.create_index('idx_notification_rules_channel', 'notification_rules', ['channel_id'], unique=False)
    op.create_index('idx_notification_rules_enabled', 'notification_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_notification_rules_alert_rule_id'), 'notification_rules', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_channel_id'), 'notification_rules', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_tenant_id'), 'notification_rules', ['tenant_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='valid_notification_queue_status'),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_queue_created', 'notification_queue', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_notification_queue_retry', 'notification_queue', ['status', 'created_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('idx_notification_queue_status', 'notification_queue', ['status'], unique=False)
    op.create_index('idx_notification_queue_tenant', 'notification_queue', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_alert_event_id'), 'notification_queue', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_tenant_id'), 'notification_queue', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('alert_event_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("delivery_status IS NULL OR delivery_status IN ('success', 'permanent_failure', 'temporary_failure', 'invalid_address', 'rate_limited')", name='valid_delivery_status'),
    sa.CheckConstraint("status IN ('pending', 'sending', 'sent', 'failed', 'bounced', 'skipped')", name='valid_notification_status'),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_alert_event', 'notifications', ['alert_event_id'], unique=False)
    op.create_index('idx_notifications_channel', 'notifications', ['channel_id'], unique=False)
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False, postgresql_using='DESC')
    op.create_index('idx_notifications_recipient', 'notifications', ['recipient'], unique=False)
    op.create_index('idx_notifications_retry', 'notifications', ['status', 'next_retry_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notifications_tenant', 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_alert_event_id'), 'notifications', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel_id'), 'notifications', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_event_id'), table_name='notifications')
    op.drop_index('idx_notifications_tenant', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_index('idx_notifications_retry', table_name='notifications', postgresql_where="status = 'pending'")
    op.drop_index('idx_notifications_recipient', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications', postgresql_using='DESC')
    op.drop_index('idx_notifications_channel', table_name='notifications')
    op.drop_index('idx_notifications_alert_event', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_queue_tenant_id'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_alert_event_id'), table_name='notification_queue')
    op.drop_index('idx_notification_queue_tenant', table_name='notification_queue')
    op.drop_index('idx_notification_queue_status', table_name='notification_queue')
    op.drop_index('idx_notification_queue_retry', table_name='notification_queue', postgresql_where="status = 'pending'")
    op.drop_index('idx_notification_queue_created', table_name='notification_queue', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_notification_rules_tenant_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_channel_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_alert_rule_id'), table_name='notification_rules')
    op.drop_index('idx_notification_rules_enabled', table_name='notification_rules')
    op.drop_index('idx_notification_rules_channel', table_name='notification_rules')
    op.drop_index('idx_notification_rules_alert', table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_alert_rule_conditions_rule_id'), table_name='alert_rule_conditions')
    op.drop_index('idx_alert_conditions_rule', table_name='alert_rule_conditions')
    op.drop_table('alert_rule_conditions')
    op.drop_index(op.f('ix_alert_events_tenant_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_fired_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_device_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_index('idx_alert_events_status', table_name='alert_events')
    op.drop_index('idx_alert_events_severity', table_name='alert_events')
    op.drop_index('idx_alert_events_rule', table_name='alert_events')
    op.drop_index('idx_alert_events_device', table_name='alert_events')
    op.drop_index('idx_alert_events_alarm_type', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alarms_tenant_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_status'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_severity'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_fired_at'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_device_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alert_rule_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alarm_type'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_acknowledged_by'), table_name='alarms')
    op.drop_index('idx_alarms_active', table_name='alarms', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_alarms_acknowledged', table_name='alarms', postgresql_where=sa.text('acknowledged_by IS NOT NULL'))
    op.drop_table('alarms')
    op.drop_index(op.f('ix_telemetry_hot_timestamp'), table_name='telemetry_hot')
    op.drop_index(op.f('ix_telemetry_hot_tenant_id'), table_name='telemetry_hot')
    op.drop_index(op.f('ix_telemetry_hot_device_id'), table_name='telemetry_hot')
    op.drop_index('idx_telemetry_timestamp', table_name='telemetry_hot')
    op.drop_index('idx_telemetry_tenant_device', table_name='telemetry_hot')
    op.drop_index('idx_telemetry_device_time', table_name='telemetry_hot')
    op.drop_table('telemetry_hot')
    op.drop_index(op.f('ix_group_devices_group_id'), table_name='group_devices')
    op.drop_index(op.f('ix_group_devices_device_id'), table_name='group_devices')
    op.drop_index('idx_group_devices_group', table_name='group_devices')
    op.drop_index('idx_group_devices_device', table_name='group_devices')
    op.drop_table('group_devices')
    op.drop_index(op.f('ix_device_credentials_tenant_id'), table_name='device_credentials')
    op.drop_index('idx_creds_tenant_device', table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_severity'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_device_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_active'), table_name='alert_rules')
    op.drop_index('idx_alert_rules_device', table_name='alert_rules')
    op.drop_index('idx_alert_rules_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_group_bulk_operations_tenant_id'), table_name='group_bulk_operations')
    op.drop_index(op.f('ix_group_bulk_operations_group_id'), table_name='group_bulk_operations')
    op.drop_index('idx_bulk_operations_tenant', table_name='group_bulk_operations')
    op.drop_index('idx_bulk_operations_status', table_name='group_bulk_operations')
    op.drop_index('idx_bulk_operations_group', table_name='group_bulk_operations')
    op.drop_index('idx_bulk_operations_created_at', table_name='group_bulk_operations')
    op.drop_table('group_bulk_operations')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_group_id'), table_name='devices')
    op.drop_index('idx_devices_tenant_dev_eui', table_name='devices')
    op.drop_index('idx_devices_status', table_name='devices')
    op.drop_index('idx_devices_site', table_name='devices')
    op.drop_index('idx_devices_organization', table_name='devices')
    op.drop_index('idx_devices_last_seen', table_name='devices')
    op.drop_index('idx_devices_group', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_groups_tenant_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_site_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_organization_id'), table_name='device_groups')
    op.drop_index('idx_device_groups_tenant', table_name='device_groups')
    op.drop_index('idx_device_groups_site', table_name='device_groups')
    op.drop_index('idx_device_groups_org', table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index('idx_sites_tenant', table_name='sites')
    op.drop_index('idx_sites_parent', table_name='sites')
    op.drop_index('idx_sites_organization', table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_tenant_id'), table_name='notification_channels')
    op.drop_index('idx_notification_channels_user', table_name='notification_channels')
    op.drop_index('idx_notification_channels_type', table_name='notification_channels')
    op.drop_index('idx_notification_channels_tenant', table_name='notification_channels')
    op.drop_index('idx_notification_channels_enabled', table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('idx_users_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index('idx_organizations_tenant', table_name='organizations')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_index('idx_organizations_chirpstack', table_name='organizations', postgresql_where='chirpstack_app_id IS NOT NULL')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_index('idx_notification_templates_tenant', table_name='notification_templates')
    op.drop_index('idx_notification_templates_enabled', table_name='notification_templates')
    op.drop_index('idx_notification_templates_channel', table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_composite_alert_rules_tenant_id'), table_name='composite_alert_rules')
    op.drop_index(op.f('ix_composite_alert_rules_severity'), table_name='composite_alert_rules')
    op.drop_index(op.f('ix_composite_alert_rules_enabled'), table_name='composite_alert_rules')
    op.drop_table('composite_alert_rules')
    # ### end Alembic commands ###
